### ISSUE TITLE
Text at the bottom overlapping at 1280 x 800 resolution

### ISSUE THREAD

**Issue by davidauza-engineer** [onedebos/my-portfolio#4]
The text is overlapping as shown below:

<img width="1280" alt="Screen Shot 2019-11-28 at 4 23 07 PM" src="https://user-images.githubusercontent.com/47565678/69832566-1b431280-11fd-11ea-906c-1b9d41b73d32.png">

I am proposing a solution found on the following pull request: 

https://github.com/onedebos/my-portfolio/pull/3

Regards,

David Auza

**Comment by onedebos** [comment]
Thanks David.
